name: Test and Build

on: [workflow_dispatch]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Verification des fichiers présent dans le runner
        run: ls -a -l
      - name: Clone du projet dans le runner (checkout)
        uses: actions/checkout@v6  
      - name: Verification des fichiers après l'action "checkout"
        run: ls -a -l 
